# Generated by Django 3.0.5 on 2022-12-09 03:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonate',
            name='survey_answer',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
