# Generated by Django 3.0.5 on 2022-12-10 04:12

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_blooddonate_survey_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonate',
            name='survey_answer',
            field=jsonfield.fields.JSONField(),
        ),
    ]
