# Generated by Django 3.0.5 on 2022-12-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='proof',
            field=models.ImageField(null=True, upload_to='proof/'),
        ),
    ]
