# Generated by Django 3.0.5 on 2022-12-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='proof',
        ),
    ]
