# Generated by Django 3.0.5 on 2022-11-23 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
        ('blood', '0005_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hepaB', models.BooleanField()),
                ('hepaC', models.BooleanField()),
                ('hiv1', models.BooleanField()),
                ('hiv2', models.BooleanField()),
                ('htlv1', models.BooleanField()),
                ('htlv2', models.BooleanField()),
                ('syphilis', models.BooleanField()),
                ('westNile', models.BooleanField()),
                ('trypanosomaC', models.BooleanField()),
                ('babesia', models.BooleanField()),
                ('bloodDonate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.BloodDonate')),
            ],
        ),
    ]
