# Generated by Django 3.0.5 on 2022-11-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_bloodtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_patient',
        ),
    ]
