# Generated by Django 3.0.5 on 2022-12-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_bloodrequest_request_by_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='unit_approved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
