# Generated by Django 3.0.5 on 2022-12-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_bloodrequest_unit_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='proof',
            field=models.ImageField(null=True, upload_to='proof/'),
        ),
    ]
